// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCheJcMEM9tN3JrDbPmDdZVBb1zHOgmVgE',
    appId: '1:91995083959:web:c503fd0acf71a06a716932',
    messagingSenderId: '91995083959',
    projectId: 'alpha-app-2a332',
    authDomain: 'alpha-app-2a332.firebaseapp.com',
    storageBucket: 'alpha-app-2a332.firebasestorage.app',
    measurementId: 'G-PSP1JDZ7QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQVk54yu55bNsUuXn0QtOm5oWkMN9orL0',
    appId: '1:91995083959:android:33b382700e12226d716932',
    messagingSenderId: '91995083959',
    projectId: 'alpha-app-2a332',
    storageBucket: 'alpha-app-2a332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNzxcIgcGZTFenKgHxebNNsV5ch1GZcD0',
    appId: '1:91995083959:ios:ba778c41dfab3d9f716932',
    messagingSenderId: '91995083959',
    projectId: 'alpha-app-2a332',
    storageBucket: 'alpha-app-2a332.firebasestorage.app',
    iosBundleId: 'com.example.alphaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNzxcIgcGZTFenKgHxebNNsV5ch1GZcD0',
    appId: '1:91995083959:ios:ba778c41dfab3d9f716932',
    messagingSenderId: '91995083959',
    projectId: 'alpha-app-2a332',
    storageBucket: 'alpha-app-2a332.firebasestorage.app',
    iosBundleId: 'com.example.alphaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCheJcMEM9tN3JrDbPmDdZVBb1zHOgmVgE',
    appId: '1:91995083959:web:7fb6432bd7966899716932',
    messagingSenderId: '91995083959',
    projectId: 'alpha-app-2a332',
    authDomain: 'alpha-app-2a332.firebaseapp.com',
    storageBucket: 'alpha-app-2a332.firebasestorage.app',
    measurementId: 'G-5Q0JKLB1XK',
  );
}
